// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "ecd4146d-2cc5-4688-9dd3-074ad19248e5");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1604644697);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1604644817);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1604974943);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1604648057);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1604645057);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1604644577);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1604645177);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1604644937);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1543800004);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{67cff516-54c2-46ad-a315-b76c4f1f743d}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1543737600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1543800005);
user_pref("browser.onboarding.notification.tour-ids-queue", "");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.state", "watermark");
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1604648064817");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1604649885817");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1604644438324");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1604666038324");
user_pref("browser.search.region", "KR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181023215924");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1604974913");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20181023215924");
user_pref("browser.startup.homepage_override.mstone", "63.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1543800007040");
user_pref("devtools.debugger.ignore-caught-exceptions", false);
user_pref("devtools.debugger.prefs-schema-version", "1.0.4");
user_pref("devtools.inspector.activeSidebar", "computedview");
user_pref("devtools.inspector.three-pane-first-run", false);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "94dbc5bc0af649bfad7b3fc70e068681");
user_pref("extensions.blocklist.lastModified", "Wed, 04 Nov 2020 15:24:28 GMT");
user_pref("extensions.blocklist.pingCountTotal", 8);
user_pref("extensions.blocklist.pingCountVersion", 8);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1604644698);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181023215924");
user_pref("extensions.lastAppVersion", "63.0");
user_pref("extensions.lastPlatformVersion", "63.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{244b431e-9176-4a36-9ea6-7cb708968a56}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"2f1a1a86-5940-42a7-86b3-b74cc952d68a\",\"webcompat@mozilla.org\":\"732e1df7-2b1b-42c2-996e-f35fc745cf17\",\"screenshots@mozilla.org\":\"89911247-90c1-45a3-82c9-7d1aff395333\",\"fxmonitor@mozilla.org\":\"c0f57ead-d7e8-45e5-a046-06aa7a6cb7c3\",\"baidu-code-update@mozillaonline.com\":\"20a30173-febc-4ddf-87e6-c72f94b23ffc\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1604644849);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1543800157);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181023215924");
user_pref("media.gmp-manager.lastCheck", 1604568576);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1604644849);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2b4e7a8f-8525-4282-a3d2-f365cc0285d8");
user_pref("services.blocklist.addons.checked", 1604976044);
user_pref("services.blocklist.gfx.checked", 1604976044);
user_pref("services.blocklist.onecrl.checked", 1604976044);
user_pref("services.blocklist.pinning.checked", 1604976044);
user_pref("services.blocklist.plugins.checked", 1604976044);
user_pref("services.settings.clock_skew_seconds", -1130);
user_pref("services.settings.last_etag", "\"1604968730335\"");
user_pref("services.settings.last_update_seconds", 1604976044);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1604976044);
user_pref("services.settings.main.tippytop.last_check", 1604976044);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1603094833);
user_pref("toolkit.startup.last_success", 1604974912);
user_pref("toolkit.telemetry.cachedClientID", "ee7c27ae-6e4e-4a18-bdf6-80f9bc5200d7");
user_pref("toolkit.telemetry.previousBuildID", "20181023215924");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
